### ISSUE TITLE
Support for display reCAPTCHA from AJAX API

### ISSUE THREAD

**Issue by reypm** [genemu/GenemuFormBundle#362]
I'm just wondering, since I didn't see nothing at config level, if this bundle supports for display reCAPTCHA from AJAX API as explained [here](https://developers.google.com/recaptcha/docs/display#AJAX) if it's supported any example around configuration to take care?

**Comment by emimarz** [comment]
Sorry for my ignorance, that code give me an error
Variable "public_key" does not exist in blablabla.html.twig in line
where this is            Recaptcha.create('{{ public_key }}', '{{ id }}_div', {{ configs|json_encode|raw }});

how can I fix that?
