### ISSUE TITLE
Bundle still maintained?

### ISSUE THREAD

**Issue by lunetics** [genemu/GenemuFormBundle#415]
It seems this Bundle is abandoned. Did anyone get ahold of @genemu ?

**Comment by fcpauldiaz** [comment]
I think this bundle is no longer maintained, last release was December 2014.

**Comment by vaziuok** [comment]
Is there an alternative bundle?

**Comment by fcpauldiaz** [comment]
There are some individual bundles for almost every feature of this bundle, what feature are you looking for?

**Comment by vaziuok** [comment]
@fcpauldiaz Thank you for your answer. We are searching for a bundle which makes us easier to implement datepicker and Select2 in our application running the newest version of Symfony (> 3.0). Do you have any idea?

**Comment by fcpauldiaz** [comment]
I use both of that features. For the select2  [download](https://select2.github.io/) the javascripts and css, from the official page add them to your project, initialize it via jQuery and add: class="select2" when ever you want to use it. For the datetime picker you can use the [stephanecollot/DatetimepickerBundle](https://github.com/stephanecollot/DatetimepickerBundle)

**Comment by bamarni** [comment]
I'm currently discussing with @genemu about moving the repo to an organization, we might also clean it up to focus on most used types (captcha, recaptcha, select2, plain) so that it is easier to maintain.

So indeed the bundle is unmaintained at the moment but we want to fix this, sorry for the delay.

**Comment by nlzet** [comment]
@bamarni did you make a decision, or is there more news about the future of this bundle ?

**Comment by Think-It** [comment]
up

**Comment by Think-It** [comment]
@bamarni Up :)

**Comment by bamarni** [comment]
What is making this bundle hard to be maintained is that : 
- we accepted too many types, while a lot of them have not much to do with a backend application, so shouldn't live in a symfony bundle
- Even though some pending PRs look good, builds are failing all over the place and fixing the CI isn't trivial.

I've just opened a PR here #421 with some suggestions :
- supporting symfony 2.7, 2.8 and symfony 3 only (symfony 2.3 will reach end of support in may)
- focusing on relevant types

I also moved all the tests to a backup directory, fixed and included back a few of them (Captcha, Recaptcha), just to have a working CI we can use as a base.

Let me know if you have some other suggestions or want to tweak the supported type list. cc @genemu

**Comment by bamarni** [comment]
As there is no feedback, I'll go on and merge my PR. It won't break stuff anyway, 3.X is just removing documentation / tests for types I don't plan to support anymore, they will eventually be removed in a next major version bump. Until then, that list can still be adjusted of course.

Moving the repo to a new place seems complicated, for now I'll try to at least add a co-maintainer. @Soullivaneuh I remember you were interested about this, is it still the case?

**Comment by Soullivaneuh** [comment]
> supporting symfony 2.7, 2.8 and symfony 3 only (symfony 2.3 will reach end of support in may)

Should be done on a new major release of this library, but agree.

> @Soullivaneuh I remember you were interested about this, is it still the case?

Even if I have less time than when I proposed my help, I can still try to do things yes. ;-)

**Comment by alexislefebvre** [comment]
@bamarni 

> symfony 2.3 will reach end of support in may

Yes and no. Symfony2.3 will reach *End of support for bug fixes* in May and *End of support for security fixes* on May 2017. So Symfony 2.3 may still be used until May 2017.

Source: http://symfony.com/roadmap?version=2.3#checker

**Comment by bamarni** [comment]
@Soullivaneuh great news :) just asked @genemu about it, there is already a new major version (https://github.com/genemu/GenemuFormBundle/blob/master/UPGRADE%203.0.md)

@alexislefebvre : we can follow this too, if security patches are needed that shouldn't be a big deal for maintenance

**Comment by Soullivaneuh** [comment]
Is not really a big deal to stop support SF 2.3 on a new major right now. If the old one is stable enough, security fixes of Symfony should not influence on bundles...

**Comment by bamarni** [comment]
We now have a plan and @Soullivaneuh as a co-maintainer, I guess this can be closed. Thanks for initiating this @lunetics.
