### ISSUE TITLE
[Question] Release version 3.0

### ISSUE THREAD

**Issue by aivus** [genemu/GenemuFormBundle#443]
Hi folks

Do you have plans to release stable 3.0 version with support of Symfony 3.x?

**Comment by vitaliyberdylo** [comment]
I am also interested in this issue.

**Comment by vitaliyberdylo** [comment]
Looks like GenemuFormBundle still use removed in Symfony 3.0 methods.
For example PropertyAccess::getPropertyAccessor()
here https://github.com/genemu/GenemuFormBundle/blob/master/Form/Model/ChoiceList/AjaxModelChoiceList.php#L92

**Comment by aivus** [comment]
@vitaliyberdylo it has lots things which were removed since 3.0

**Comment by vitaliyberdylo** [comment]
@aivus yes but according composer.json GenemuFormBundle should support Symfony 3
https://github.com/genemu/GenemuFormBundle/commit/e85b1c80543c58e792d4b4373c98241be6acc8ba

**Comment by sglessard** [comment]
@vitaliyberdylo It does not
